name: Modus Wealth
favicon: null
layout_spectrum: 0.8948123510926962
typography_spectrum: 0.80376
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#400040'
    - '#ffffff'
    - '#61c100'
    - '#dbcfdb'
    - '#875f87'
  brandStrength: 0.07037320523522794
  lightness: 0.7316549993120134
  saturation: 0.554852913832292
  rhythmicContrast: 0.9680651088710874
purpose: []
